language: cpp

dist: trusty
sudo: required

before_install: sudo apt-get update -qq

install:
  - sudo apt-get install libboost-filesystem-dev
  - sudo apt-get install libgtest-dev

before_script:
  - mkdir gtest_build
  - cd gtest_build
  - cp -r /usr/src/gtest/* ./
  - cmake CMakeLists.txt
  - make
  - sudo cp *.a /usr/lib
  - cd ..
  - rm -rf gtest_build
  - cmake -DWITH_CLING=OFF -DBOOST_FILESYSTEM=ON .

script: make

compiler:
  - clang
  - gcc
